# Generated by Django 3.2.6 on 2021-08-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_stock_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=200, null=True)),
                ("ticker", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
