# Generated by Django 3.2.6 on 2021-08-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_username"),
        ("projects", "0005_rename_watchlists_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="user_id",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="watcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
