# Generated by Django 3.2.6 on 2021-08-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_rename_ticker_watchlist_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="stock",
            new_name="ticker",
        ),
    ]
