# Generated by Django 3.2.6 on 2021-08-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_rename_stock_watchlist_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watcher",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
